services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodata:/data/db
    networks:
      - mongodb_network
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongoexp
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - mongodb_network

  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    volumes:
      - serverdata:/usr/src/server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - mongodb_network



volumes:
  mongodata:
  serverdata:


networks:
  mongodb_network:
    driver: bridge